### ISSUE TITLE
Broken range?

### ISSUE THREAD

**Issue by kyonifer** [ujmp/universal-java-matrix-package#5]
Running

```
DenseMatrix.Factory.range(3.0,3.0)
```

yields the error

```
Exception in thread "main" java.lang.NullPointerException
    at org.ujmp.core.calculation.AbstractCalculation.<init>(AbstractCalculation.java:43)
    at org.ujmp.core.doublematrix.calculation.AbstractDoubleCalculation.<init>(AbstractDoubleCalculation.java:40)
    at org.ujmp.core.doublematrix.calculation.entrywise.creators.Range.<init>(Range.java:39)
    at org.ujmp.core.matrix.factory.AbstractMatrixFactory.range(AbstractMatrixFactory.java:574)
    at org.ujmp.core.matrix.factory.AbstractMatrixFactory.range(AbstractMatrixFactory.java:578)
```

looks like AbstractMatrixFactory.java:574 is passing in null which eventually gets stuck as a null.length in AbstractCalculation.java:43

**Comment by holger-arndt** [comment]
You're right, this should not happen. It's fixed now in the development branch.
