### ISSUE TITLE
get Exception when running example code.

### ISSUE THREAD

**Issue by Robert-Lu** [ujmp/universal-java-matrix-package#6]
I got

**Uncaught error fetching image:
java.lang.NullPointerException
    at sun.awt.image.URLImageSource.getConnection(Unknown Source)
    at sun.awt.image.URLImageSource.getDecoder(Unknown Source)
    at sun.awt.image.InputStreamImageSource.doFetch(Unknown Source)
    at sun.awt.image.ImageFetcher.fetchloop(Unknown Source)
    at sun.awt.image.ImageFetcher.run(Unknown Source)**

with the code

```
// create matrix with 10 correlated columns, 100 rows, correlation 0.1
Matrix correlated = Matrix.Factory.correlatedColumns(10, 10, 0.1);

// calculate similarity and store in new matrix,
// ignore missing values if present
Matrix similarity = correlated.cosineSimilarity(Ret.NEW, true);

// show on screen
correlated.showGUI();
similarity.showGUI();
```

In fact, if the showGUI method used for more than once, there will be an exception.

And, when I use `java -jar ujmp-complete.jar` . It raised exception when I click _Examples - Matrix - Welcome Matrix_

---

Some extra info:
java version 1.8.0_45
and .. I'm still student and not sure whether it is because of my mistake.

Thanks!

**Comment by holger-arndt** [comment]
You're doing everything right and I believe I know where the problem is. Sometimes I got the same exception with Java 8. This wasn't a problem with Java 7. Thought I had fixed it, but it still seems to be there. I need to investigate further.

**Comment by holger-arndt** [comment]
The problem should be fixed now in the development branch. Can you try again?

**Comment by cuisquare** [comment]
Just to mention I am running into the same issue. I will try the fix proposed and report on the result.

**Comment by cuisquare** [comment]
Just to mention I do not know how to use the development version. I have successfully imported the development repository and by default imported all the projects with it. Now my limited knowledge means that I do not know how to use those in my project. I'm using eclipse, and I only know how to use libraries imported with Jars. Unless you have a link I can look into, I will actually only be able to report once I know how to do the above.

**Comment by holger-arndt** [comment]
Maven should pretty much take care of all the dependencies. Just add ujmp-core to your pom file and it should be fine. Are you sure, you checked out the branch "develop" with the latest changes?

**Comment by ChrizZz110** [comment]
This problem still exists in the current release.

**Comment by JuanMorenoS** [comment]
I have the same error

**Comment by ghost** [comment]
I have the exact same error as OP described in current version too whenever I try and use certain functionalities in the GUI.

java version "1.8.0_201"

Java(TM) SE Runtime Environment (build 1.8.0_201-b09)

Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)

**Comment by warnotte** [comment]
Same here with maven version 0.3.0 :(
